### ISSUE TITLE
Pagination by models.collections

### ISSUE THREAD

**Issue by rochzp** [webgradus/kms_models#19]
Hi,

Here I have a scenario which there is a new list on my site. I want to make it in pagination via `models.news`. But I have no idea how to implement this feature. Any example?

And how can I get the size of `models.news`.

Looking forward to someone can give me a help. Thx.

**Comment by GarPit** [comment]
Hello, @rochzp 

Thanks for using APIQ CMS. For size of collection use this: http://evilmartians.github.io/liquor/language-spec.html#size

For example,

    {% assign size = size(models.news) %}

Is it correct that you want a pagination for your `models.news` collection?

**Comment by rochzp** [comment]
Thank you for the solution！

**Comment by GarPit** [comment]
You're welcome!
